version: "3.8"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
      target: "database"
    ports:
      - "5432:5432"
    volumes:
      - pgdate:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: "Asia/Tokyo"
    restart: always
volumes:
  pgdate:
